language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer # Updates JDK 8 to the latest available.

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    # TODO

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
